listen_addresses = ['127.0.0.1:1053']
server_names = ['dnscrypt-ip4-filter-pri', 'dnscrypt-ip4-filter-alt', 'dnscrypt-ip4-filter-alt2', 'dnscrypt-ip6-filter-pri', 'dnscrypt-ip6-filter-alt', 'dnscrypt-ip6-filter-alt2']

# https://quad9.net/dnscrypt/quad9-resolvers-dnscrypt.md

[static.'dnscrypt-ip4-filter-pri']
# Quad9 (anycast) dnssec/no-log/filter 9.9.9.9
stamp = "sdns://AQMAAAAAAAAADDkuOS45Ljk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0"

[static.'dnscrypt-ip4-filter-alt']
# Quad9 (anycast) dnssec/no-log/filter 149.112.112.9
stamp = "sdns://AQMAAAAAAAAAEjE0OS4xMTIuMTEyLjk6ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0"

[static.'dnscrypt-ip4-filter-alt2']
# Quad9 (anycast) dnssec/no-log/filter 149.112.112.112
stamp = "sdns://AQMAAAAAAAAAFDE0OS4xMTIuMTEyLjExMjo4NDQzIGfIR7jIdYzRICRVQ751Z0bfNN8dhMALjEcDaN-CHYY-GTIuZG5zY3J5cHQtY2VydC5xdWFkOS5uZXQ"

[static.'dnscrypt-ip6-filter-pri']
# Quad9 (anycast) dnssec/no-log/filter 2620:fe::fe
stamp = "sdns://AQMAAAAAAAAAElsyNjIwOmZlOjpmZV06ODQ0MyBnyEe4yHWM0SAkVUO-dWdG3zTfHYTAC4xHA2jfgh2GPhkyLmRuc2NyeXB0LWNlcnQucXVhZDkubmV0"

[static.'dnscrypt-ip6-filter-alt']
# Quad9 (anycast) dnssec/no-log/filter 2620:fe::9
stamp = "sdns://AQMAAAAAAAAAEVsyNjIwOmZlOjo5XTo4NDQzIGfIR7jIdYzRICRVQ751Z0bfNN8dhMALjEcDaN-CHYY-GTIuZG5zY3J5cHQtY2VydC5xdWFkOS5uZXQ"

[static.'dnscrypt-ip6-filter-alt2']
# Quad9 (anycast) dnssec/no-log/filter 2620:fe::fe:9
stamp = "sdns://AQMAAAAAAAAAFFsyNjIwOmZlOjpmZTo5XTo4NDQzIGfIR7jIdYzRICRVQ751Z0bfNN8dhMALjEcDaN-CHYY-GTIuZG5zY3J5cHQtY2VydC5xdWFkOS5uZXQ"
